title: Get Inspired | SUEGO
description: Get inspired by the stories of the entrepreneurs who are changing the Greater Wadshington, D.C. Region.
highlighter: rouge

baseurl: ''
url: https://www.suego.co

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'config.rb', 'sass']

enforce_ssl: suego.co
twitter_username: suegohq
github_username:  steverodrigz

# About/contact
author:
  name:              Steven A Rodriguez
  url:               https://twitter.com/steverodrigz
  email:             steven@suego.co

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/suego/suego.github.io

# Settings for sitemap_generator plugin.
sitemap:
    exclude:
        - "/rss.xml"
        - "/tag"
    include_posts:
        - "/index.html"
        - "/work/index.html"

# Collections
collections:
  case_studies:
  output: true
  permalink: /work/:slug/